version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ../sites:/srv/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/enabled.conf:/etc/nginx/sites-enabled/nithin.dfeverx.com
    # links:
    #     - phpfpm