version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ../sites:/srv/www
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./site-ava:/etc/nginx/sites-available/
      - ./site-ava:/etc/nginx/sites-enabled/
    # links:
    #     - phpfpm
